version: "3"
services:
  redis-release-master:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass changeit
  demoapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    environment:
      - MY_PASSWORD=changeit
