apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    app: demoapi
  creationTimestamp: null
  labels:
    io.kompose.service: demoapi
  name: demoapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        app: demoapi
      creationTimestamp: null
      labels:
        io.kompose.service: demoapi
    spec:
      containers:
      - image: "hmatt1/demo-api:{{ .Values.tag }}"
        name: demoapi
#        env:
#        - name: REDIS_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: demo-api-secret
#              key: REDIS_PASSWORD
        ports:
        - containerPort: 8080
        resources:
            limits: { memory: "300Mi", cpu: "200m" }
            requests: { memory: "300Mi", cpu: "200m" }
      restartPolicy: Always
status: {}
