apiVersion: v1
kind: Service
metadata:
  annotations:
    app: demoapi
  creationTimestamp: null
  labels:
    io.kompose.service: demoapi
  name: demoapi
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: demoapi
status:
  loadBalancer: {}
